### ISSUE TITLE
Rabbit hide from bats are being picked up by zombies, so they don't despawn

### ISSUE THREAD

**Issue by nktruong** [epolixa/Bityard-Fabric#11]
The first occurrence of the zombie army was first seen at Lonnie's base. Crowds of zombies in caves were holding zombie flesh were reappearing. Now, on July 9th, I have seen occurrences of this everywhere on the server, but this time with rabbit hide. With the recent events of high amounts of lag, this army is probably in full force of taking over the server.

**The fix:** remove rabbit hide from the loot table of the bats

![2022-07-09_21 24 10](https://user-images.githubusercontent.com/88857875/178127871-880342e3-55cf-40e9-aa81-82949f50c41d.png)
![2022-07-09_21 23 47](https://user-images.githubusercontent.com/88857875/178127872-9fbef629-9884-400c-a33f-e53d30382f36.png)

**Comment by epolixa** [comment]
The loot table is overridden by the datapack, not the fabric mod. Fixed in [e6bc192451b67dfba3b39338588486c4cb5b64ca](https://github.com/epolixa/Shroomhearth-Datapack/commit/e6bc192451b67dfba3b39338588486c4cb5b64ca)
